version = 1

test_patterns = ["**/*__tests__"]

exclude_patterns = [
  ".history/",
  "build/",
  "coverage/",
  "cypress/",
  "scripts/",
  "public/"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  style_guide = "standard"
  dialect = "typescript"

[[transformers]]
name = "standardjs"
enabled = true